name: Phan

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  run:
    name: Run Phan
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup PHP
        uses: ./.github/actions/setup-php

      - name: Restore cached baseline for Phan
        id: cache-baseline-restore
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            test/phan-baseline.php
          key: phan-baseline-${{ github.run_id }}"
          restore-keys: |
            phan-baseline-

      - name: Run Phan
        continue-on-error: true
        run: |
          if [ -f test/phan-baseline.php ]; then
            echo "Cached baseline for Phan is found. Running Phan with baseline."
            phan -d ./ -k .phan/config.php --load-baseline test/phan-baseline.php --output-mode=github --no-progress-bar
          else
            echo "Cached baseline for Phan is not found. Running Phan without baseline."
            phan -d ./ -k .phan/config.php --output-mode=github --no-progress-bar
            exit 0
          fi
