name: Phan

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  run:
    name: Run Phan
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@ccf2c627fe61b1b4d924adfcbd19d661a18133a0 # v2.35.2
        with:
          php-version: '8.4'
          tools: phan:5.5.1
          coverage: none

      - name: Restore cached baseline for Phan
        id: cache-baseline-restore
        uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            test/phan-baseline.php
          key: phan-baseline-${{ github.run_id }}"
          restore-keys: |
            phan-baseline-

      - name: Run Phan
        continue-on-error: true
        run: |
          if [ -f test/phan-baseline.php ]; then
            echo "Cached baseline for Phan is found. Running Phan with baseline."
            phan -d ./ -k .phan/config.php --load-baseline test/phan-baseline.php --output-mode=github --no-progress-bar
          else
            echo "Cached baseline for Phan is not found. Running Phan without baseline."
            phan -d ./ -k .phan/config.php --output-mode=github --no-progress-bar
            exit 0
          fi
