name: Test with php-src

on:
  pull_request:
    branches: [ 'master', 'main' ]
  workflow_dispatch:
  schedule:
    - cron:  '0 9 7,14,21,28 * *'

jobs:
  test:
    name: Test with php-src
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - uses: actions/checkout@v4
      - name: Run docker compose
        shell: bash
        run: |
          cp .github/workflows/php-src-${{ matrix.php }}.dockerfile Dockerfile
          docker compose up -d
          sleep 30

      - name: Run testing
        shell: bash
        run: |
          sleep 30
          docker compose run web sh -c "cd / && composer test"
