name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 15 * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3' ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run docker-compose
        shell: bash
        run: |
          cp .github/workflows/php-${{ matrix.php }}.dockerfile Dockerfile
          docker-compose up -d
          sleep 30

      - name: Run testing
        shell: bash
        run: |
          sleep 30
          docker-compose exec -T web sh -c "cd / && composer test"
