name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ 'master', 'main' ]
  workflow_dispatch:
  schedule:
    - cron:  '0 9 15 * *'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://github.com/shivammathur/setup-php?tab=readme-ov-file#cloud-osplatform-support
        os: [ 'ubuntu-22.04', 'ubuntu-24.04', 'ubuntu-22.04-arm', 'ubuntu-24.04-arm', 'windows-2022', 'macos-14', 'macos-15', 'macos-26' ]
        php-version: [ '8.1', '8.2', '8.3', '8.4', '8.5' ]
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup PHP
        uses: ./.github/actions/setup-php
        with:
          php-version: ${{ matrix.php-version }}

      - name: Prepare environment
        run: composer update

      - name: Run testing
        run: |
          php -v
          composer test
