name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ 'master', 'main' ]
  workflow_dispatch:
  schedule:
    - cron:  '0 9 15 * *'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    env:
      PHP_EXTENSIONS: mbstring, json, bcmath, zip, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, exif, gd, ldap, fileinfo
    strategy:
      matrix:
        # https://github.com/shivammathur/setup-php?tab=readme-ov-file#cloud-osplatform-support
        os: [ 'ubuntu-22.04', 'windows-2022', 'macos-14' ]
        php-version: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: ${{ env.PHP_EXTENSIONS }}

      - name: Prepare environment
        run: composer update

      - name: Run testing
        run: |
          php -v
          composer test
