name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ 'master', 'main' ]
  workflow_dispatch:
  schedule:
    - cron:  '0 9 15 * *'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    env:
      PHP_EXTENSIONS: mbstring, json, bcmath, zip, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, exif, gd, ldap, fileinfo
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          extensions: ${{ env.PHP_EXTENSIONS }}

      - name: Prepare environment
        shell: bash
        run: composer install

      - name: Run testing
        shell: bash
        run: composer test
