name: PHPStan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ 'master', 'main' ]

jobs:
  run:
    name: Run PHPStan
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        level: [ 0, 1, 2 ]
        include:
          - current-level: 0
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
        with:
          php-version: '8.3'

      - name: Install PHPStan
        run: composer require --dev phpstan/phpstan

      - name: Run PHPStan
        if:  matrix.level == matrix.current-level
        continue-on-error: true
        run: |
             ./vendor/bin/phpstan analyse -l "${{ matrix.level }}" --memory-limit 128M src test
             exit 0

      - name: Run PHPStan
        if:  matrix.level > matrix.current-level
        continue-on-error: true
        run: |
             ./vendor/bin/phpstan analyse -l "${{ matrix.level }}" --memory-limit 128M src test
             exit 0
