name: PHPStan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ 'master', 'main' ]
  pull_request_target:
    types:
      - closed

jobs:
  run:
    name: Run PHPStan
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        level: [ 1, 2 ]
        include:
          - current-level: 1
          - max-level: 2
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
        with:
          php-version: '8.4'

      - name: Remove phpDocumentor temporarily and Install PHPStan
        run: composer remove --dev --no-update phpdocumentor/phpdocumentor; composer update

      - name: Restore cached baseline for PHPStan
        id: cache-baseline-restore
        uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            test/phpstan-baseline.neon
          key: phpstan-baseline-${{ github.run_id }}"
          restore-keys: |
            phpstan-baseline-

      - name: Run PHPStan
        if: matrix.level == matrix.current-level
        continue-on-error: true
        run: |
             ./vendor/bin/phpstan analyse --memory-limit 1G -c test/phpstan.neon src test -l "${{ matrix.level }}"

      - name: Run PHPStan
        if: matrix.level > matrix.current-level
        continue-on-error: true
        run: |
             ./vendor/bin/phpstan analyse --memory-limit 1G -c test/phpstan.neon src test -l "${{ matrix.level }}"
             exit 0

      - name: Generate the baseline for PHPStan
        if: matrix.level == matrix.max-level && github.event.pull_request.merged == true
        continue-on-error: true
        run: |
             ./vendor/bin/phpstan analyse --memory-limit 1G -c test/phpstan.neon --generate-baseline test/phpstan-baseline.neon src test -vvv --debug -l "${{ matrix.level }}"
             exit 0

      - name: Save the baseline for PHPStan
        id: cache-baseline-save
        if: matrix.level == matrix.max-level && github.event.pull_request.merged == true
        uses: actions/cache/save@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            test/phpstan-baseline.neon
          key: phpstan-baseline-${{ github.run_id }}"
